// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WebKtLinkMessage.proto

package me.sttimort.webkt.protobuf;

public final class WebKtLinkMessageOuterClass {
  private WebKtLinkMessageOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface WebKtLinkMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:WebKtLinkMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string linkType = 1;</code>
     * @return The linkType.
     */
    java.lang.String getLinkType();
    /**
     * <code>string linkType = 1;</code>
     * @return The bytes for linkType.
     */
    com.google.protobuf.ByteString
        getLinkTypeBytes();

    /**
     * <code>string linkRelation = 2;</code>
     * @return The linkRelation.
     */
    java.lang.String getLinkRelation();
    /**
     * <code>string linkRelation = 2;</code>
     * @return The bytes for linkRelation.
     */
    com.google.protobuf.ByteString
        getLinkRelationBytes();

    /**
     * <code>string linkHref = 3;</code>
     * @return The linkHref.
     */
    java.lang.String getLinkHref();
    /**
     * <code>string linkHref = 3;</code>
     * @return The bytes for linkHref.
     */
    com.google.protobuf.ByteString
        getLinkHrefBytes();
  }
  /**
   * Protobuf type {@code WebKtLinkMessage}
   */
  public static final class WebKtLinkMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:WebKtLinkMessage)
      WebKtLinkMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use WebKtLinkMessage.newBuilder() to construct.
    private WebKtLinkMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private WebKtLinkMessage() {
      linkType_ = "";
      linkRelation_ = "";
      linkHref_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new WebKtLinkMessage();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private WebKtLinkMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              linkType_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              linkRelation_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              linkHref_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return me.sttimort.webkt.protobuf.WebKtLinkMessageOuterClass.internal_static_WebKtLinkMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return me.sttimort.webkt.protobuf.WebKtLinkMessageOuterClass.internal_static_WebKtLinkMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              me.sttimort.webkt.protobuf.WebKtLinkMessageOuterClass.WebKtLinkMessage.class, me.sttimort.webkt.protobuf.WebKtLinkMessageOuterClass.WebKtLinkMessage.Builder.class);
    }

    public static final int LINKTYPE_FIELD_NUMBER = 1;
    private volatile java.lang.Object linkType_;
    /**
     * <code>string linkType = 1;</code>
     * @return The linkType.
     */
    @java.lang.Override
    public java.lang.String getLinkType() {
      java.lang.Object ref = linkType_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        linkType_ = s;
        return s;
      }
    }
    /**
     * <code>string linkType = 1;</code>
     * @return The bytes for linkType.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getLinkTypeBytes() {
      java.lang.Object ref = linkType_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        linkType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LINKRELATION_FIELD_NUMBER = 2;
    private volatile java.lang.Object linkRelation_;
    /**
     * <code>string linkRelation = 2;</code>
     * @return The linkRelation.
     */
    @java.lang.Override
    public java.lang.String getLinkRelation() {
      java.lang.Object ref = linkRelation_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        linkRelation_ = s;
        return s;
      }
    }
    /**
     * <code>string linkRelation = 2;</code>
     * @return The bytes for linkRelation.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getLinkRelationBytes() {
      java.lang.Object ref = linkRelation_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        linkRelation_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LINKHREF_FIELD_NUMBER = 3;
    private volatile java.lang.Object linkHref_;
    /**
     * <code>string linkHref = 3;</code>
     * @return The linkHref.
     */
    @java.lang.Override
    public java.lang.String getLinkHref() {
      java.lang.Object ref = linkHref_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        linkHref_ = s;
        return s;
      }
    }
    /**
     * <code>string linkHref = 3;</code>
     * @return The bytes for linkHref.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getLinkHrefBytes() {
      java.lang.Object ref = linkHref_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        linkHref_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getLinkTypeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, linkType_);
      }
      if (!getLinkRelationBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, linkRelation_);
      }
      if (!getLinkHrefBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, linkHref_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getLinkTypeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, linkType_);
      }
      if (!getLinkRelationBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, linkRelation_);
      }
      if (!getLinkHrefBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, linkHref_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof me.sttimort.webkt.protobuf.WebKtLinkMessageOuterClass.WebKtLinkMessage)) {
        return super.equals(obj);
      }
      me.sttimort.webkt.protobuf.WebKtLinkMessageOuterClass.WebKtLinkMessage other = (me.sttimort.webkt.protobuf.WebKtLinkMessageOuterClass.WebKtLinkMessage) obj;

      if (!getLinkType()
          .equals(other.getLinkType())) return false;
      if (!getLinkRelation()
          .equals(other.getLinkRelation())) return false;
      if (!getLinkHref()
          .equals(other.getLinkHref())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + LINKTYPE_FIELD_NUMBER;
      hash = (53 * hash) + getLinkType().hashCode();
      hash = (37 * hash) + LINKRELATION_FIELD_NUMBER;
      hash = (53 * hash) + getLinkRelation().hashCode();
      hash = (37 * hash) + LINKHREF_FIELD_NUMBER;
      hash = (53 * hash) + getLinkHref().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static me.sttimort.webkt.protobuf.WebKtLinkMessageOuterClass.WebKtLinkMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static me.sttimort.webkt.protobuf.WebKtLinkMessageOuterClass.WebKtLinkMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static me.sttimort.webkt.protobuf.WebKtLinkMessageOuterClass.WebKtLinkMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static me.sttimort.webkt.protobuf.WebKtLinkMessageOuterClass.WebKtLinkMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static me.sttimort.webkt.protobuf.WebKtLinkMessageOuterClass.WebKtLinkMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static me.sttimort.webkt.protobuf.WebKtLinkMessageOuterClass.WebKtLinkMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static me.sttimort.webkt.protobuf.WebKtLinkMessageOuterClass.WebKtLinkMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static me.sttimort.webkt.protobuf.WebKtLinkMessageOuterClass.WebKtLinkMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static me.sttimort.webkt.protobuf.WebKtLinkMessageOuterClass.WebKtLinkMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static me.sttimort.webkt.protobuf.WebKtLinkMessageOuterClass.WebKtLinkMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static me.sttimort.webkt.protobuf.WebKtLinkMessageOuterClass.WebKtLinkMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static me.sttimort.webkt.protobuf.WebKtLinkMessageOuterClass.WebKtLinkMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(me.sttimort.webkt.protobuf.WebKtLinkMessageOuterClass.WebKtLinkMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code WebKtLinkMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:WebKtLinkMessage)
        me.sttimort.webkt.protobuf.WebKtLinkMessageOuterClass.WebKtLinkMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return me.sttimort.webkt.protobuf.WebKtLinkMessageOuterClass.internal_static_WebKtLinkMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return me.sttimort.webkt.protobuf.WebKtLinkMessageOuterClass.internal_static_WebKtLinkMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                me.sttimort.webkt.protobuf.WebKtLinkMessageOuterClass.WebKtLinkMessage.class, me.sttimort.webkt.protobuf.WebKtLinkMessageOuterClass.WebKtLinkMessage.Builder.class);
      }

      // Construct using me.sttimort.webkt.protobuf.WebKtLinkMessageOuterClass.WebKtLinkMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        linkType_ = "";

        linkRelation_ = "";

        linkHref_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return me.sttimort.webkt.protobuf.WebKtLinkMessageOuterClass.internal_static_WebKtLinkMessage_descriptor;
      }

      @java.lang.Override
      public me.sttimort.webkt.protobuf.WebKtLinkMessageOuterClass.WebKtLinkMessage getDefaultInstanceForType() {
        return me.sttimort.webkt.protobuf.WebKtLinkMessageOuterClass.WebKtLinkMessage.getDefaultInstance();
      }

      @java.lang.Override
      public me.sttimort.webkt.protobuf.WebKtLinkMessageOuterClass.WebKtLinkMessage build() {
        me.sttimort.webkt.protobuf.WebKtLinkMessageOuterClass.WebKtLinkMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public me.sttimort.webkt.protobuf.WebKtLinkMessageOuterClass.WebKtLinkMessage buildPartial() {
        me.sttimort.webkt.protobuf.WebKtLinkMessageOuterClass.WebKtLinkMessage result = new me.sttimort.webkt.protobuf.WebKtLinkMessageOuterClass.WebKtLinkMessage(this);
        result.linkType_ = linkType_;
        result.linkRelation_ = linkRelation_;
        result.linkHref_ = linkHref_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof me.sttimort.webkt.protobuf.WebKtLinkMessageOuterClass.WebKtLinkMessage) {
          return mergeFrom((me.sttimort.webkt.protobuf.WebKtLinkMessageOuterClass.WebKtLinkMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(me.sttimort.webkt.protobuf.WebKtLinkMessageOuterClass.WebKtLinkMessage other) {
        if (other == me.sttimort.webkt.protobuf.WebKtLinkMessageOuterClass.WebKtLinkMessage.getDefaultInstance()) return this;
        if (!other.getLinkType().isEmpty()) {
          linkType_ = other.linkType_;
          onChanged();
        }
        if (!other.getLinkRelation().isEmpty()) {
          linkRelation_ = other.linkRelation_;
          onChanged();
        }
        if (!other.getLinkHref().isEmpty()) {
          linkHref_ = other.linkHref_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        me.sttimort.webkt.protobuf.WebKtLinkMessageOuterClass.WebKtLinkMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (me.sttimort.webkt.protobuf.WebKtLinkMessageOuterClass.WebKtLinkMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object linkType_ = "";
      /**
       * <code>string linkType = 1;</code>
       * @return The linkType.
       */
      public java.lang.String getLinkType() {
        java.lang.Object ref = linkType_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          linkType_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string linkType = 1;</code>
       * @return The bytes for linkType.
       */
      public com.google.protobuf.ByteString
          getLinkTypeBytes() {
        java.lang.Object ref = linkType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          linkType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string linkType = 1;</code>
       * @param value The linkType to set.
       * @return This builder for chaining.
       */
      public Builder setLinkType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        linkType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string linkType = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearLinkType() {
        
        linkType_ = getDefaultInstance().getLinkType();
        onChanged();
        return this;
      }
      /**
       * <code>string linkType = 1;</code>
       * @param value The bytes for linkType to set.
       * @return This builder for chaining.
       */
      public Builder setLinkTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        linkType_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object linkRelation_ = "";
      /**
       * <code>string linkRelation = 2;</code>
       * @return The linkRelation.
       */
      public java.lang.String getLinkRelation() {
        java.lang.Object ref = linkRelation_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          linkRelation_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string linkRelation = 2;</code>
       * @return The bytes for linkRelation.
       */
      public com.google.protobuf.ByteString
          getLinkRelationBytes() {
        java.lang.Object ref = linkRelation_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          linkRelation_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string linkRelation = 2;</code>
       * @param value The linkRelation to set.
       * @return This builder for chaining.
       */
      public Builder setLinkRelation(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        linkRelation_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string linkRelation = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearLinkRelation() {
        
        linkRelation_ = getDefaultInstance().getLinkRelation();
        onChanged();
        return this;
      }
      /**
       * <code>string linkRelation = 2;</code>
       * @param value The bytes for linkRelation to set.
       * @return This builder for chaining.
       */
      public Builder setLinkRelationBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        linkRelation_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object linkHref_ = "";
      /**
       * <code>string linkHref = 3;</code>
       * @return The linkHref.
       */
      public java.lang.String getLinkHref() {
        java.lang.Object ref = linkHref_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          linkHref_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string linkHref = 3;</code>
       * @return The bytes for linkHref.
       */
      public com.google.protobuf.ByteString
          getLinkHrefBytes() {
        java.lang.Object ref = linkHref_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          linkHref_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string linkHref = 3;</code>
       * @param value The linkHref to set.
       * @return This builder for chaining.
       */
      public Builder setLinkHref(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        linkHref_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string linkHref = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearLinkHref() {
        
        linkHref_ = getDefaultInstance().getLinkHref();
        onChanged();
        return this;
      }
      /**
       * <code>string linkHref = 3;</code>
       * @param value The bytes for linkHref to set.
       * @return This builder for chaining.
       */
      public Builder setLinkHrefBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        linkHref_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:WebKtLinkMessage)
    }

    // @@protoc_insertion_point(class_scope:WebKtLinkMessage)
    private static final me.sttimort.webkt.protobuf.WebKtLinkMessageOuterClass.WebKtLinkMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new me.sttimort.webkt.protobuf.WebKtLinkMessageOuterClass.WebKtLinkMessage();
    }

    public static me.sttimort.webkt.protobuf.WebKtLinkMessageOuterClass.WebKtLinkMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<WebKtLinkMessage>
        PARSER = new com.google.protobuf.AbstractParser<WebKtLinkMessage>() {
      @java.lang.Override
      public WebKtLinkMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new WebKtLinkMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<WebKtLinkMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<WebKtLinkMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public me.sttimort.webkt.protobuf.WebKtLinkMessageOuterClass.WebKtLinkMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_WebKtLinkMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_WebKtLinkMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026WebKtLinkMessage.proto\"L\n\020WebKtLinkMes" +
      "sage\022\020\n\010linkType\030\001 \001(\t\022\024\n\014linkRelation\030\002" +
      " \001(\t\022\020\n\010linkHref\030\003 \001(\tB\034\n\032me.sttimort.we" +
      "bkt.protobufb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_WebKtLinkMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_WebKtLinkMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_WebKtLinkMessage_descriptor,
        new java.lang.String[] { "LinkType", "LinkRelation", "LinkHref", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
